### PR TITLE
Discover minor modes with `discover-my-mode`

### PR DESCRIPTION
**Pull request by jguenther**
This is a pretty bare-bones implementation of minor mode discovery that uses the methods defined in this package. I refactored a bit to allow the discovery of bindings in a buffer for an arbitrary minor mode, but `discover-my-major` should work as before.

It seems to work fairly well. One possible problem is that the minibuffer prompt for selecting a minor mode doesn't exclude modes that have no bindings in the buffer, but I couldn't think of an efficient way of doing that--filtering the list passed to `completing-read` by `dmm/mode-has-bindings-p` induces a noticable slowdown for buffers with a lot of minor modes.

I'm not sure if this is something you'd be interested in merging in, given the name of this package, but I've found it useful already.

Thoughts?

### CODE REVIEW

**Comment by jguenther** [comment]
One thing that would be nice is if the list of bindings would display the actual binding instead of ` <remap> <orig-command>` for remapped commands.

**Comment by steckerhalter** [comment]
thanks for the PR. could you add some documentation to the README so that people can discover your enhancement?

**Comment by jguenther** [comment]
Ah yeah, good point.

One odd thing is that I can't seem to get the autoload cookie to take effect. I don't think I've ever used that feature myself, but it may be because I'm loading this package directly from my checked out repo instead of adding a `package.el` source for it, etc.

**Comment by steckerhalter** [comment]
Yes, package.el creates autoloads automatically. I didn't even study the manual autoload facility because it "just works" like that.

**Comment by steckerhalter** [comment]
looks good, can I merge?

**Comment by jguenther** [comment]
Yup if you're good with it I am. Everything *seems* to work that used to.

**Pull request merged**
